export enum BodyTypeEnum {
  SEDAN = 'SEDAN',
  HATCHBACK = 'HATCHBACK',
  UNIVERSAL = 'UNIVERSAL',
  COUPE = 'COUPE',
  CONVERTIBLE = 'CONVERTIBLE',
  SUV = 'SUV',
  PICKUP = 'PICKUP',
  MINIVEN = 'MINIVEN',
  FURGON = 'FURGON',
  LIMUZIN = 'LIMUZIN',
}
