export enum CategoryEnum {
  PASSENGER = 'PASSENGER',
  TRUCK = 'TRUCK',
  MOTOTECHNICS = 'MOTOTECHNICS',
  SPECIAL_TECHNICS = 'SPECIAL_TECHNICS',
  BUS = 'BUS',
  TRAILER = 'TRAILER',
  WATER_TECHNOLOGY = 'WATER_TECHNOLOGY',
}
